name: Trigger auto deployment for container-app-6hkva5bfplcag

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-6hkva5bfplcag-AutoDeployTrigger-e0d34609-79b1-449d-aeb2-d822569b78b2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP6HKVA5BFPLCAG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP6HKVA5BFPLCAG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP6HKVA5BFPLCAG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP6HKVA5BFPLCAG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP6HKVA5BFPLCAG_REGISTRY_PASSWORD }}
          containerAppName: container-app-6hkva5bfplcag
          resourceGroup: appspacesragapp901fb68f
          imageToBuild: default/container-app-6hkva5bfplcag:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


